### ISSUE TITLE
Not working on golem anymore?

### ISSUE THREAD

**Issue by ingoschaefer** [devattendant/one-page-reader#1]
Hello Sebastian,

it seems to me the plugin is not doing his job on golem.de anymore.
(I would have written this plugin myself now, but you have done a good job so far.)

As it is working well for heise.de I assume it correctly installed and active.

Can you give me hints, how to debug the extension? The JavaScript does not seem to have diagnostic output built in.

Regards,
Ingo

**Comment by devattendant** [comment]
Hi Ingo,

Thanks for pointing that golem is/was not working. They slightly modified the HTML code for the urls of further pages, that's why detection failed. I've fixed the error, committed the new code and updated FF and Chrome listings.

I will try to find some time to add some diagnostic output in future time, otherwise feel free to contribute :)

**Comment by ingoschaefer** [comment]
Hello Sebastian,
thank you for addressing the issue and updating the plugin.
The "main" functionality is working again, the removing of the TOC seems to be not working. I think gsidetoc might be the right id to search for.

As an improvment I will suggest to just modify the toc to link to the (now concatenated) parts of the article as internal links instead of removing them.

**Comment by devattendant** [comment]
As of 2022 golem prevents fetching site content with Javascript, therefore golem is not working at the moment. If anyone has suggestions on how to solve this issue, feel free to share.
